{% set name = "kubernetes-kind" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes-sigs/kind/archive/v{{ version }}.tar.gz
  sha256: 016c36750be5c5fb81f70e4675ee0a4f278dd929f05273184ff68cae112ce71b

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - ripgrep
  commands:
    - kind --help
    - kind --version | rg {{ version }}

about:
  summary: Kubernetes IN Docker - local clusters for testing Kubernetes
  home: https://github.com/kubernetes-sigs/kind
  license: Apache-2.0
  license_file:
    - LICENSE
    - thirdparty/

extra:
  recipe-maintainers:
    - dhirschfeld
