{% set name = "kubernetes-kind" %}
{% set version = "0.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes-sigs/kind/archive/v{{ version }}.tar.gz
  sha256: eb7bcb8005ff980d7d7ad088165a5a6236f484444aa397520cd98cb046e1d797

build:
  skip: true  # [win]
  number: 1

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - ripgrep
  commands:
    - kind --help
    - kind --version | rg {{ version }}

about:
  summary: Kubernetes IN Docker - local clusters for testing Kubernetes
  home: https://github.com/kubernetes-sigs/kind
  license: Apache-2.0
  license_file:
    - LICENSE
    - thirdparty/

extra:
  recipe-maintainers:
    - dhirschfeld
