{% set name = "kubernetes-kind" %}
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes-sigs/kind/archive/v{{ version }}.tar.gz
  sha256: 841dd2fdc5c194e1ea49f36204cce33a943285862303713a1baa5d2073cdb0d9

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - ripgrep
  commands:
    - kind --help
    - kind --version | rg {{ version }}

about:
  summary: Kubernetes IN Docker - local clusters for testing Kubernetes
  home: https://github.com/kubernetes-sigs/kind
  license: Apache-2.0
  license_file:
    - LICENSE
    - thirdparty/

extra:
  recipe-maintainers:
    - dhirschfeld
