{% set name = "kubernetes-kind" %}
{% set version = "0.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes-sigs/kind/archive/v{{ version }}.tar.gz
  sha256: 6b0ae7748144034ba296a302f5aaaad7120aef4df9d8138cc6276a43ca3c96d1

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - ripgrep
  commands:
    - kind --help
    - kind --version | rg {{ version }}

about:
  summary: Kubernetes IN Docker - local clusters for testing Kubernetes
  home: https://github.com/kubernetes-sigs/kind
  license: Apache-2.0
  license_file:
    - LICENSE
    - thirdparty/

extra:
  recipe-maintainers:
    - dhirschfeld
